# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20150513_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
