# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20160803_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise',
            name='analiseAnterior',
        ),
        migrations.AddField(
            model_name='analise',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
