# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20160809_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimentoporperiodo',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
