# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-21 14:47
from __future__ import unicode_literals

from django.db import migrations, models


def setQuandoFromPeriodo(apps, schema_editor):
    pontos = apps.get_model('backend', 'ponto')
    for ponto in pontos.objects.all().iterator():
        ponto.quando = ponto.periodo.data
        ponto.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rendimentoporperiodo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='quando',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(setQuandoFromPeriodo),
        migrations.AlterField(
            model_name='ponto',
            name='quando',
            field=models.DateField(),
        ),
    ]
