# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_ponto_quando'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='pontoAnterior',
        ),
    ]
