# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_ponto_pontoanterior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ['-ativo', '-ponto__quando', '-data_hora_atualizacao', '-data_hora_criacao']},
        ),
        migrations.AlterModelOptions(
            name='ponto',
            options={'ordering': ['-ativo', '-quando', '-data_hora_atualizacao', '-data_hora_criacao']},
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='periodo',
        ),
    ]
