# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models

def setQuandoFromPeriodo(apps, schema_editor):
    analises = apps.get_model('backend', 'analise')
    for analise in analises.objects.all().iterator():
        analise.quando = analise.periodo.data
        analise.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20170720_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='quando',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(setQuandoFromPeriodo),
        migrations.AlterField(
            model_name='analise',
            name='quando',
            field=models.DateField(),
        ),
    ]