# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models

def setQuandoFromPeriodo(apps, schema_editor):
    analisesporperiodo = apps.get_model('backend', 'analiseporperiodo')
    for analiseporperiodo in analisesporperiodo.objects.all().iterator():
        analiseporperiodo.quando = analiseporperiodo.periodo.data
        analiseporperiodo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_analise_quando'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analise',
            options={'ordering': ['-ativo', '-quando', '-data_hora_atualizacao', '-data_hora_criacao']},
        ),
        migrations.RemoveField(
            model_name='analise',
            name='periodo',
        ),
        migrations.AddField(
            model_name='analiseporperiodo',
            name='quando',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(setQuandoFromPeriodo),
        migrations.AlterField(
            model_name='analiseporperiodo',
            name='quando',
            field=models.DateField(),
        ),
    ]
'''
        migrations.AddField(
            model_name='analiseporperiodo',
            name='quando',
            field=models.DateField(default=999),
            preserve_default=False,
        ),
'''