# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20170720_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analiseporperiodo',
            options={'ordering': ['-ativo', '-quando', '-data_hora_atualizacao', '-data_hora_criacao'], 'verbose_name_plural': 'analises por periodo'},
        ),
        migrations.RemoveField(
            model_name='analiseporperiodo',
            name='periodo',
        ),
    ]
