# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def setContaFromPonto(apps, schema_editor):
    movimentos = apps.get_model('backend', 'movimento')
    for movimento in movimentos.objects.all().iterator():
        movimento.conta = movimento.ponto.conta
        movimento.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20170721_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Conta'),
        ),
        migrations.RunPython(setContaFromPonto),
        migrations.AlterField(
            model_name='movimento',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Conta'),
        ),
    ]