# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_movimento_conta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ['-ativo', '-quando', '-data_hora_atualizacao', '-data_hora_criacao']},
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='ponto',
        ),
    ]
