# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 20:59
from __future__ import unicode_literals

from django.db import migrations

def setValorFromOperacao(apps, schema_editor):
    movimentos = apps.get_model('backend', 'movimento')
    for movimento in movimentos.objects.all().iterator():
        if (movimento.operacao == 'DE'):
            movimento.valor *= -1
        movimento.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20170721_1311'),
    ]

    operations = [
        migrations.RunPython(setValorFromOperacao),
    ]