# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_remove_movimento_operacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='operacao',
        ),
    ]
