CREATE USER pims WITH
	LOGIN
	SUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'viniciusmayer';

CREATE DATABASE pims
    WITH 
    OWNER = pims
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;